### ISSUE TITLE
实验性功能（添加/删除用户）bug

### ISSUE THREAD

**Issue by sysfox** [Qexo/Scripts#1]
我也不知道该怎么描述，自己看图吧
<img width="1440" alt="截屏2023-01-15 08 26 22" src="https://user-images.githubusercontent.com/99103591/212503141-e4ef39ab-1942-43d9-9e84-e6643410ce96.png">
<img width="1440" alt="截屏2023-01-15 08 26 33" src="https://user-images.githubusercontent.com/99103591/212503144-e360dd38-8450-466b-9726-25e6d071d0dc.png">
<img width="1440" alt="截屏2023-01-15 08 26 49" src="https://user-images.githubusercontent.com/99103591/212503145-7df41e91-4a62-41f4-a8af-1d545ee3f70b.png">
<img width="1440" alt="截屏2023-01-15 08 26 53" src="https://user-images.githubusercontent.com/99103591/212503146-6c0f9f11-012e-4985-a87c-edc12547fcfe.png">

**Comment by am-abudu** [comment]
目前只有MongoDB出现了这个问题，我将继续排查

**Comment by am-abudu** [comment]
经过排查，我认为是上游依赖出现问题。我使用了另一种方法解决了这个问题，请现在进行测试 962a51c0248c034e9b6710c84849f2f9ce08c297

**Comment by sysfox** [comment]
啦啦啦，功能正常
